### ISSUE TITLE
Enable Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by zamazan4ik** [sponkurtus2/GemFetch#1]
Hi!

I noticed that in the `Cargo.toml` file Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a little bit (it's not a critical issue at all for the project but anyway!). If you want to read more about LTO and its possible modes, I recommend starting from [this](https://doc.rust-lang.org/rustc/codegen-options/index.html#lto) Rustc documentation.

I think you can enable LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most optimized version of the application. However, if we enable it on the Cargo profile level for the Release profile, users, who install the application with `cargo install` will get the LTO-optimized version of the game "automatically". E.g., check `cargo-outdated` Release [profile](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L48). You also could be interested in other optimization options like `codegen-units = 1`, etc.

Basically, it can be enabled with the following lines:

```
[profile.release]
lto = true
```

I have made quick tests (Fedora 41, Rust 1.82, the latest version of the project) by adding `lto = true` to the Release profile. The binary size reduction is from 497 Kib to 441 Kib.

Thank you.

**Comment by sponkurtus2** [comment]
Hey!

Thank you for your detailed  feedback! It was very interesting, and I’ve already applied it to the project based on your recommendations. Enabling LTO, as you suggested, made a tiny difference, but still a difference and it was funny.

Your explanation about how this benefits maintainers and users installing via cargo install was particularly helpful. I’ll definitely look into exploring other optimization options like codegen-units as well. Thanks again for taking the time to share this!
