### ISSUE TITLE
Unknown WM

### ISSUE THREAD

**Issue by 0323pin** [sponkurtus2/GemFetch#2]
Hi,

I know this is early days but (and without looking at the code), I wonder why my WM is "unknown".
Also, ... "unknownBSD"?

![2024-12-17-221704_700x216_scrot](https://github.com/user-attachments/assets/c7f44138-c6e6-4065-beda-868b8d964870)

Well, I might actually understand the WM (it's actually not that common) but ...

![2024-12-17-221839_804x337_scrot](https://github.com/user-attachments/assets/00ab3693-b948-49db-9056-57d8b7ba1858)

This is cool :+1

**Comment by sponkurtus2** [comment]
Hey, I appreciate your comment, apparently the "unknown" message is a bug, I'll try to figure out why it happens and I'll fix it, thank you!

**Comment by 0323pin** [comment]
Nice, looking forward to test.
If you don't mind, as this is an binary and, not a library, please don't hide `Cargo.lock` in `.gitignore`. It makes it "harder" to package.

**Comment by sponkurtus2** [comment]
Hey!, I'm trying to fix that and I had some question, does marswm modify the `$XDG_CURRENT_DESKTOP`?

**Comment by sponkurtus2** [comment]
I just uploaded 0.1.4 and I believe I fixed the bug, can you please confirm?

**Comment by 0323pin** [comment]
Partially, yes. Thanks.

![2024-12-18-043831_747x381_scrot](https://github.com/user-attachments/assets/1f0a1db5-e9e6-4d3e-853b-ff158cfa5182)

I had this issue before with other fetchers, see https://github.com/charklie/rsftch/issues/1

Unfortunately, this was quite sometime ago and I don't remember the details. It does work on `rsftch` these days.

Off to work soon and away from my laptop but, I'll give it a try later today if you find a solution when looking at `rsftch`.

**Comment by sponkurtus2** [comment]
Hi, I'll take a look at the info you provided and tell you if I fix anything, also, I see that you're using NetBSD with marswm, I looked at marswm and it looks awesome, I'd like to give it a try on my virtual machine with NetBSD but I don't understand the installation, is there any way to reach you so you could help me, thanks.

**Comment by 0323pin** [comment]
> is there any way to reach you so you could help me, thanks.

Yes, I'm on Matrix it you use it.
@0323pin:converser.eu

Else, I'm a member of the NetBSD foundation. So, you can always use old fashion e-mail 🤣 

**EDIT:** removed personal information.

**Comment by sponkurtus2** [comment]
I took a read on the fix from rsftch, and applied to my fetch, can you try now please?

**Comment by 0323pin** [comment]
> I took a read on the fix from rsftch, and applied to my fetch, can you try now please?

Yes, of course. I want to make a package for this 😉 

All good,

![2024-12-18-210236_1366x768_scrot](https://github.com/user-attachments/assets/8bf36f04-172b-4229-95ff-74b74e3b0235)

**Comment by sponkurtus2** [comment]
Yay!!!, thank you so much for all your help ^^ and glad you liked it.

**Comment by 0323pin** [comment]
As for the package, we currently have a commit freeze (only bug fixes allowed) as we are about to cut a stable package branch. But, as soon as this is over (probably one week), I'll merge a package for it.

Will let you know when it's done.

**Comment by sponkurtus2** [comment]
Ok I'll wait for it, really appreciate it :).

**Comment by 0323pin** [comment]
Hi, I have a package ready to be merged once the commit freeze is over.

Built inside pkgsrc ;)

![2024-12-22-174545_1366x768_scrot](https://github.com/user-attachments/assets/1c5f4138-55b5-4a58-b519-dfea968d161a)

**Comment by sponkurtus2** [comment]
Hey!, aaaaa so coool ^^,  can't wait till my package is merged, once again thank you very much:D.
